spring.application.name=iso8583-adapter-core

# Server Connection Settings
adapter.server.port=8080
adapter.server.max-threads=200
adapter.tcp.nodelay=true
adapter.tcp.keepalive=true

# ISO 8583 Protocol Specs
# Length of the MLI (Message Length Indicator) - usually 2 or 4 bytes
adapter.iso.header-length=2
adapter.iso.encoding=US-ASCII
adapter.iso.use-secondary-bitmap=true

# Timeout Configurations (Critical for < 200ms SLA)
# Time to wait for HSM response
adapter.timeout.hsm-ms=50
# Time to wait for Core Banking/Database
adapter.timeout.db-ms=70
# Total processing grace period before sending '96' (System Malfunction)
adapter.timeout.total-threshold-ms=180

# Security (Masking sensitive data in logs)
adapter.logging.mask-pan=true
adapter.logging.mask-cvv=true